import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { cookies } from 'next/headers'
import MainLayoutContent from '@/components/MainLayout'
import { UserProvider } from '@/context/UserContext'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookieStore = await cookies()
  const sessionID = cookieStore.get('sessionID')?.value

  let user = null
  if (sessionID) {
    // Backend API hívás a user adatokért
    const res = await fetch('http://localhost:8080/api/user/me', {
      headers: { Cookie: `sessionID=${sessionID}` },
      cache: 'no-store'
    })
    if (res.ok) user = await res.json()
  }

  return (
    <html lang="hu">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <UserProvider user={user}>
          <MainLayoutContent>{children}</MainLayoutContent>
        </UserProvider>
      </body>
    </html>
  )
}
