services:
  # Backend Service (NestJS)
  backend:
    build:
      context: ./backend
      target: development
    container_name: betting_mentor_backend
    environment:
      - DATABASE_URL=postgresql://sp3_user:sp3_password@postgres:5432/sp3_db?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - NODE_ENV=development
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/usr/src/app
      - ./pdfconverter:/usr/src/pdfconverter
      - ./webscrapper:/usr/src/webscrapper
      - ./betmentors:/usr/src/betmentors
      - ./merge_json_data:/usr/src/app/merge_json_data
    networks:
      - betting_mentor_network
    depends_on:
      - postgres
      - redis
    command: ./wait-for-it.sh postgres:5432 -- bash -c "pnpm prisma db push --accept-data-loss && pnpm run start:dev"
    restart: unless-stopped
    mem_limit: 2g

  # Frontend Service (Next.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: betting_mentor_frontend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    networks:
      - betting_mentor_network
    depends_on:
      - backend
    restart: unless-stopped

  # PostgreSQL Database
  postgres:
    image: postgres:16-alpine
    container_name: betting_mentor_postgres
    environment:
      POSTGRES_USER: sp3_user
      POSTGRES_PASSWORD: sp3_password
      POSTGRES_DB: sp3_db
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - betting_mentor_network
    restart: unless-stopped

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: betting_mentor_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    networks:
      - betting_mentor_network
    restart: unless-stopped

  # pgAdmin (Optional - for database management)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: betting_mentor_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bettingmentor.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - betting_mentor_network
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:

networks:
  betting_mentor_network:
    driver: bridge